---
title: "Lab 06 - Conveying the right message through visualisation"
author: [i_see_a_spaceship_in_the_sky]
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(lubridate)
```


### Exercise 1

```{r create-data}
df <- tribble(
  ~date, ~mask_count, ~no_mask_count,
  "7/12/2020", 25.5, 9.9,
  "7/13/2020", 19.8, 9,
  "7/14/2020", 19.6, 9.4,
  "7/15/2020", 20.4, 9.9,
  "7/16/2020", 20, 10,
  "7/17/2020", 20, 9.5,
  "7/18/2020", 20.4, 9.4,
  "7/19/2020", 20, 9.1,
  "7/20/2020", 20.5, 8.6,
  "7/21/2020", 21.3, 8.6,
  "7/22/2020", 20, 8.7,
  "7/23/2020", 19.7, 8.6,
  "7/24/2020", 20.3, 9.9,
  "7/25/2020", 19, 10,
  "7/26/2020", 19.7, 10.1,
  "7/27/2020", 17, 9.4,
  "7/28/2020", 16.6, 9.6,
  "7/29/2020", 16.7, 9.6,
  "7/30/2020", 16.8, 10,
  "7/31/2020", 16.1, 8.9,
  "8/1/2020", 16.2, 9,
  "8/2/2020", 15.9, 8.9,
  "8/3/2020", 16, 9
)

df <- df %>%
  mutate(date = mdy(date))

df
  
```


### Exercise 2

```{r better-viz}
ggplot(data = df) +
  geom_line(mapping = aes(x = date, y = mask_count), color = "red")+
  geom_line(mapping = aes(x = date, y = no_mask_count), color = "blue") +
  labs(x = "Date", 
       y = "Rolling Average of Daily Cases Per 100K Population",
       title = "Kansas COVID-19 Cases",
       subtitle = "By Mask and No-mask Counties")

```


### Exercise 3

*Add your narrative here.*


### Exercise 4

*Add your narrative here.*
